<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");?>
<?global $docsFilter;
$docsFilter=array("UF_URL"=>$APPLICATION->GetCurDir());
$langUp=strtoupper($_SESSION["SESS_LANG_UI"]);
$lang=$_SESSION["SESS_LANG_UI"];
$APPLICATION->IncludeComponent(
	"niit:highloadblock.docs", 
	"docList", 
	array(
		"lang"=>$lang,
		"langUp"=>$langUp,
		"BLOCK_ID" => "2",
		"CHECK_PERMISSIONS" => "Y",
		"DETAIL_URL" => "",
		"FILTER_NAME" => "docsFilter",
		"PAGEN_ID" => "page",
		"ROWS_PER_PAGE" => "",
		"SORT_FIELD" => "ID",//UF_SORT
		"SORT_ORDER" => "ASC",//DESC
		"COMPONENT_TEMPLATE" => "docList"
	),
	false
);?>
<?	//иные документы
		$DOCFilter=Array("IBLOCK_ID" => 20,"ACTIVE" => "Y",'PROPERTY_PAGE'=>$APPLICATION->GetCurDir());
		$_GLOBALS['DOCFilter']=$DOCFilter;
		$APPLICATION->IncludeComponent(
			"bitrix:catalog.section", 
		"doctree", 
		array(
			"lang"=>$lang,
			"langUp"=>$langUp,
			"BACKURL"=> $APPLICATION->GetCurDir(),
			"PAGE"=>$APPLICATION->GetCurDir(),
			"ACTION_VARIABLE" => "action",
			"ADD_PROPERTIES_TO_BASKET" => "N",
			"ADD_SECTIONS_CHAIN" => "N",
			"ADD_TO_BASKET_ACTION" => "ADD",
			"AJAX_MODE" => "Y",
			"AJAX_OPTION_ADDITIONAL" => "",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_JUMP" => "Y",
			"AJAX_OPTION_STYLE" => "Y",
			"BACKGROUND_IMAGE" => "",
			"BASKET_URL" => "/personal/basket.php",
			"BROWSER_TITLE" => "",
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "N",
			"CACHE_TIME" => "36000",
			"CACHE_TYPE" => "N",
			"CONVERT_CURRENCY" => "N",
			"DETAIL_URL" => "",
			"DISABLE_INIT_JS_IN_COMPONENT" => "N",
			"DISPLAY_BOTTOM_PAGER" => "N",
			"DISPLAY_TOP_PAGER" => "N",
			"ELEMENT_SORT_FIELD" => "sort",
			"ELEMENT_SORT_FIELD2" => "id",
			"ELEMENT_SORT_ORDER" => "desc",
			"ELEMENT_SORT_ORDER2" => "desc",
			"FILTER_NAME" => "DOCFilter",
			"HIDE_NOT_AVAILABLE" => "N",
			"IBLOCK_ID" => "20",
			"IBLOCK_TYPE" => "Documents",
			"INCLUDE_SUBSECTIONS" => "Y",
			"LINE_ELEMENT_COUNT" => "50",
			"MESSAGE_404" => "",
			"MESS_BTN_ADD_TO_BASKET" => "В корзину",
			"MESS_BTN_BUY" => "Купить",
			"MESS_BTN_DETAIL" => "Подробнее",
			"MESS_BTN_SUBSCRIBE" => "Подписаться",
			"MESS_NOT_AVAILABLE" => "Нет в наличии",
			"META_DESCRIPTION" => "-",
			"META_KEYWORDS" => "-",
			"OFFERS_LIMIT" => "0",
			"PAGER_BASE_LINK_ENABLE" => "N",
			"PAGER_DESC_NUMBERING" => "N",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
			"PAGER_SHOW_ALL" => "N",
			"PAGER_SHOW_ALWAYS" => "N",
			"PAGER_TEMPLATE" => ".default",
			"PAGER_TITLE" => "Товары",
			"PAGE_ELEMENT_COUNT" => "10000",
			"PARTIAL_PRODUCT_PROPERTIES" => "N",
			"PRICE_CODE" => array(
			),
			"PRICE_VAT_INCLUDE" => "N",
			"PRODUCT_ID_VARIABLE" => "id",
			"PRODUCT_PROPERTIES" => array(
			),
			"PRODUCT_PROPS_VARIABLE" => "prop",
			"PRODUCT_QUANTITY_VARIABLE" => "",
			"PRODUCT_SUBSCRIPTION" => "N",
			"PROPERTY_CODE" => array(
				0 => "PODRAZD",
				1 => "FILE",
				2 => "",
			),
			"SECTION_CODE" => "",
			"SECTION_ID" => "",
			"SECTION_START_ID" => "20",
			"SECTION_ID_VARIABLE" => "SECTION_ID",
			"SECTION_URL" => $returnUrl,
			"SECTION_USER_FIELDS" => array(
				0 => "",
				1 => "",
			),
			"SEF_MODE" => "N",
			"SET_BROWSER_TITLE" => "N",
			"SET_LAST_MODIFIED" => "N",
			"SET_META_DESCRIPTION" => "N",
			"SET_META_KEYWORDS" => "N",
			"SET_STATUS_404" => "N",
			"SET_TITLE" => "N",
			"SHOW_404" => "N",
			"SHOW_ALL_WO_SECTION" => "Y",
			"SHOW_CLOSE_POPUP" => "N",
			"SHOW_DISCOUNT_PERCENT" => "N",
			"SHOW_OLD_PRICE" => "N",
			"SHOW_PRICE_COUNT" => "1",
			"TEMPLATE_THEME" => "blue",
			"USE_MAIN_ELEMENT_SECTION" => "N",
			"USE_PRICE_COUNT" => "N",
			"USE_PRODUCT_QUANTITY" => "N",
			"COMPONENT_TEMPLATE" => "doctree",
			"ADD_PICT_PROP" => "-",
			"LABEL_PROP" => "-",
			"CUSTOM_FILTER" => "",
			"HIDE_NOT_AVAILABLE_OFFERS" => "N",
			"COMPOSITE_FRAME_MODE" => "N",
			"COMPOSITE_FRAME_TYPE" => "AUTO",
			"DISPLAY_COMPARE" => "N",
			"COMPATIBLE_MODE" => "Y"
		),
		false
	);
?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>